#include <vox/numbers/0.h>
#include <vox/numbers/1.h>
#include <vox/numbers/2.h>
#include <vox/numbers/3.h>
#include <vox/numbers/4.h>
#include <vox/numbers/5.h>
#include <vox/numbers/6.h>
#include <vox/numbers/7.h>
#include <vox/numbers/8.h>
#include <vox/numbers/9.h>
